# Generated by Django 2.2.4 on 2020-06-01 20:31

import concord.actions.customfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_auto_20200603_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='governor_condition',
            field=concord.actions.customfields.TemplateField(default=concord.actions.customfields.Template, system=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='owner_condition',
            field=concord.actions.customfields.TemplateField(default=concord.actions.customfields.Template, system=True),
        ),
        migrations.AlterField(
            model_name='defaultcommunity',
            name='governor_condition',
            field=concord.actions.customfields.TemplateField(default=concord.actions.customfields.Template, system=True),
        ),
        migrations.AlterField(
            model_name='defaultcommunity',
            name='owner_condition',
            field=concord.actions.customfields.TemplateField(default=concord.actions.customfields.Template, system=True),
        ),
    ]
