# Generated by Django 2.2.4 on 2020-09-20 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0004_auto_20200601_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='defaultcommunity',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defaultcommunity_models', to=settings.AUTH_USER_MODEL),
        ),
    ]
