# Generated by Django 2.2.13 on 2020-10-09 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_auto_20200920_1424'),
        ('conditionals', '0006_conditionmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='governor_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities_community_governor_conditioned', to='conditionals.ConditionManager'),
        ),
        migrations.AlterField(
            model_name='community',
            name='owner_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities_community_owner_conditioned', to='conditionals.ConditionManager'),
        ),
        migrations.AlterField(
            model_name='defaultcommunity',
            name='governor_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities_defaultcommunity_governor_conditioned', to='conditionals.ConditionManager'),
        ),
        migrations.AlterField(
            model_name='defaultcommunity',
            name='owner_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities_defaultcommunity_owner_conditioned', to='conditionals.ConditionManager'),
        ),
    ]
