# Generated by Django 2.2.13 on 2020-10-09 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_auto_20200920_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='governor_condition',
        ),
        migrations.RemoveField(
            model_name='community',
            name='owner_condition',
        ),
        migrations.RemoveField(
            model_name='defaultcommunity',
            name='governor_condition',
        ),
        migrations.RemoveField(
            model_name='defaultcommunity',
            name='owner_condition',
        ),
    ]