# Generated by Django 2.2.4 on 2020-05-09 20:07

import concord.permission_resources.customfields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('foundational_permission_enabled', models.BooleanField(default=False)),
                ('governing_permission_enabled', models.BooleanField(default=True)),
                ('data', concord.permission_resources.customfields.TemplateDataField(default=concord.permission_resources.customfields.TemplateData, null=True)),
                ('description', models.CharField(max_length=500)),
                ('owner_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_resources_template_owned_objects', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PermissionsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('foundational_permission_enabled', models.BooleanField(default=False)),
                ('governing_permission_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inverse', models.BooleanField(default=False)),
                ('permitted_object_id', models.PositiveIntegerField()),
                ('actors', concord.permission_resources.customfields.ActorListField(default=concord.permission_resources.customfields.ActorList)),
                ('roles', concord.permission_resources.customfields.RoleListField(default=concord.permission_resources.customfields.RoleList)),
                ('change_type', models.CharField(max_length=200)),
                ('configuration', models.CharField(default='{}', max_length=5000)),
                ('owner_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_resources_permissionsitem_owned_objects', to='contenttypes.ContentType')),
                ('permitted_object_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
