# Generated by Django 2.2.4 on 2020-05-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission_resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionsitem',
            name='anyone',
            field=models.BooleanField(default=False),
        ),
    ]
