# Generated by Django 2.2.4 on 2020-06-01 20:31

import concord.actions.customfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission_resources', '0003_auto_20200531_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionsitem',
            name='condition',
            field=concord.actions.customfields.TemplateField(default=concord.actions.customfields.Template, system=True),
        ),
    ]
