# Generated by Django 2.2.13 on 2020-10-09 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permission_resources', '0004_permissionsitem_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionsitem',
            name='condition',
        ),
    ]
