# Generated by Django 2.2.13 on 2020-10-09 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permission_resources', '0004_permissionsitem_creator'),
        ('conditionals', '0006_conditionmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionsitem',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_resources_permissionsitem_conditioned', to='conditionals.ConditionManager'),
        ),
    ]
