# Generated by Django 2.2.13 on 2020-10-09 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permission_resources', '0006_auto_20201009_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionsitem',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_resources_permissionsitem_conditioned', to='conditionals.ConditionManager'),
        ),
    ]
