# Generated by Django 2.2.13 on 2021-04-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission_resources', '0006_auto_20210414_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionsitem',
            name='configuration',
        ),
    ]
