# Generated by Django 2.2.4 on 2020-08-22 20:19

import concord.actions.customfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('actions', '0001_initial'), ('actions', '0002_auto_20200520_1924'), ('actions', '0003_auto_20200522_2015'), ('actions', '0004_auto_20200523_2006'), ('actions', '0005_actioncontainer_trigger_action'), ('actions', '0006_actioncontainer_is_system'), ('actions', '0007_auto_20200621_1646'), ('actions', '0008_templatemodel'), ('actions', '0009_actioncontainer_trigger_action_pk'), ('actions', '0010_auto_20200715_1546'), ('actions', '0011_auto_20200804_1905'), ('actions', '0012_auto_20200822_2018')]

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('foundational_permission_enabled', models.BooleanField(default=False)),
                ('governing_permission_enabled', models.BooleanField(default=True)),
                ('template_data', concord.actions.customfields.TemplateField(default=concord.actions.customfields.Template)),
                ('scopes', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=90, unique=True)),
                ('user_description', models.CharField(max_length=500)),
                ('supplied_fields', models.CharField(max_length=500)),
                ('owner_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_templatemodel_owned_objects', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('change', concord.actions.customfields.StateChangeField()),
                ('resolution', concord.actions.customfields.ResolutionField(default=concord.actions.customfields.Resolution)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('is_draft', models.BooleanField(default=False)),
                ('status', models.CharField(default='created', max_length=15)),
            ],
        ),
    ]
