# Generated by Django 2.1.2 on 2018-10-20 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('change_type', models.CharField(blank=True, max_length=50)),
                ('change_data', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Drafted'), ('sent', 'Sent, awaiting approval'), ('appr', 'Approved'), ('rejct', 'Rejected'), ('wdrwn', 'Withdrawn'), ('impl', 'Implemented')], default='draft', max_length=5)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
