# Generated by Django 2.2.4 on 2020-05-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actioncontainer',
            name='status',
        ),
        migrations.AddField(
            model_name='actioncontainer',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='actioncontainer',
            name='summary_status',
            field=models.CharField(default='drafted', max_length=20),
        ),
        migrations.AlterField(
            model_name='action',
            name='container',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
