# Generated by Django 2.2.4 on 2020-09-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_squashed_0012_auto_20200822_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='status',
        ),
    ]
