# Generated by Django 2.1.2 on 2018-10-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('draft', 'Drafted'), ('sent', 'Sent, awaiting approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('implemented', 'Implemented')], default='draft', max_length=5),
        ),
    ]
