# Generated by Django 2.2.4 on 2020-09-20 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0003_auto_20200914_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemodel',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templatemodel_models', to=settings.AUTH_USER_MODEL),
        ),
    ]
