# Generated by Django 2.2.13 on 2020-11-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_templatemodel_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='resolution',
        ),
        migrations.AddField(
            model_name='action',
            name='logs',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='status',
            field=models.CharField(default='default', max_length=15),
        ),
        migrations.AddField(
            model_name='action',
            name='template_info',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
