# Generated by Django 2.2.4 on 2020-05-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_auto_20200523_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='actioncontainer',
            name='trigger_action',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
