# Generated by Django 2.2.13 on 2021-02-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_auto_20201118_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='template_info',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
