# Generated by Django 2.2.4 on 2020-06-21 16:46

import concord.actions.customfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_actioncontainer_is_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actioncontainer',
            name='action_info',
        ),
        migrations.RemoveField(
            model_name='actioncontainer',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='actioncontainer',
            name='is_system',
        ),
        migrations.RemoveField(
            model_name='actioncontainer',
            name='trigger_action',
        ),
        migrations.AddField(
            model_name='actioncontainer',
            name='context',
            field=concord.actions.customfields.TemplateContextField(default=concord.actions.customfields.TemplateContext),
        ),
        migrations.AddField(
            model_name='actioncontainer',
            name='template_data',
            field=concord.actions.customfields.TemplateField(default=concord.actions.customfields.Template),
        ),
        migrations.AlterField(
            model_name='action',
            name='resolution',
            field=concord.actions.customfields.ResolutionField(default=concord.actions.customfields.Resolution),
        ),
    ]
