# Generated by Django 2.2.4 on 2020-07-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0008_templatemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='actioncontainer',
            name='trigger_action_pk',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
