# Generated by Django 2.2.4 on 2020-07-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0009_actioncontainer_trigger_action_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actioncontainer',
            name='summary_status',
        ),
        migrations.AddField(
            model_name='actioncontainer',
            name='status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
