# Generated by Django 2.2.4 on 2020-08-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0010_auto_20200715_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action',
            name='status',
            field=models.CharField(default='created', max_length=15),
        ),
    ]
