# Generated by Django 2.1.2 on 2018-12-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200)),
                ('owner_type', models.CharField(choices=[('ind', 'Individually Owned'), ('com', 'Community Owned')], default='ind', max_length=3)),
                ('foundational_permission_enabled', models.BooleanField(default=False)),
                ('governing_permission_enabled', models.BooleanField(default=True)),
                ('action', models.IntegerField()),
                ('approved', models.BooleanField(null=True)),
                ('self_approval_allowed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConditionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200)),
                ('owner_type', models.CharField(choices=[('ind', 'Individually Owned'), ('com', 'Community Owned')], default='ind', max_length=3)),
                ('foundational_permission_enabled', models.BooleanField(default=False)),
                ('governing_permission_enabled', models.BooleanField(default=True)),
                ('condition_type', models.CharField(max_length=400)),
                ('condition_data', models.CharField(blank=True, max_length=400, null=True)),
                ('permission_data', models.CharField(blank=True, max_length=400, null=True)),
                ('conditioned_object', models.IntegerField()),
                ('conditioning_choices', models.CharField(default='permission', max_length=18)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoteCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200)),
                ('owner_type', models.CharField(choices=[('ind', 'Individually Owned'), ('com', 'Community Owned')], default='ind', max_length=3)),
                ('foundational_permission_enabled', models.BooleanField(default=False)),
                ('governing_permission_enabled', models.BooleanField(default=True)),
                ('action', models.IntegerField()),
                ('yeas', models.IntegerField(default=0)),
                ('nays', models.IntegerField(default=0)),
                ('allow_abstain', models.BooleanField(default=True)),
                ('abstains', models.IntegerField(default=0)),
                ('require_majority', models.BooleanField(default=False)),
                ('publicize_votes', models.BooleanField(default=False)),
                ('voted', models.CharField(default='[]', max_length=500)),
                ('voting_starts', models.DateTimeField(auto_now_add=True)),
                ('voting_period', models.IntegerField(default=168)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
