# Generated by Django 2.1.2 on 2018-12-06 18:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votecondition',
            name='voting_period',
            field=models.DecimalField(decimal_places=3, default=Decimal('168.0'), max_digits=4),
        ),
    ]
