# Generated by Django 2.2.4 on 2020-06-21 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conditionals', '0002_auto_20200601_1313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConditionTemplate',
        ),
    ]
