# Generated by Django 2.2.4 on 2020-09-20 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conditionals', '0003_delete_conditiontemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalcondition',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvalcondition_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='votecondition',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votecondition_models', to=settings.AUTH_USER_MODEL),
        ),
    ]
