# Generated by Django 2.2.13 on 2020-10-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditionals', '0006_conditionmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvalcondition',
            old_name='source_id',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='consensuscondition',
            old_name='source_id',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='votecondition',
            old_name='source_id',
            new_name='source',
        ),
        migrations.AddField(
            model_name='approvalcondition',
            name='element_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consensuscondition',
            name='element_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votecondition',
            name='element_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
