# Generated by Django 2.2.13 on 2021-04-05 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20200920_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='owner_content_type',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
