# Generated by Django 2.2.13 on 2021-04-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20210423_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplelist',
            name='description',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
