# Generated by Django 2.2.13 on 2021-05-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_auto_20210423_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentor',
            new_name='commenter',
        ),
    ]
