# Generated by Django 2.2.13 on 2021-05-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_auto_20210504_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplelist',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
