# Generated by Django 2.2.13 on 2021-05-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_auto_20210512_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simplelist',
            old_name='row_configuration',
            new_name='columns',
        ),
    ]
